# GDB specific options
handle SIG38 noprint
handle SIGUSR2 noprint
set debug-file-directory /usr/lib/debug/
set disassembly-flavor intel
set print pretty on

# S2E configuration options
set environment S2E_CONFIG=s2e-config.lua
set environment S2E_SHARED_DIR=/home/sjz/S2E/s2e/build/libs2e-debug/x86_64-s2e-softmmu/
set environment LD_PRELOAD=/home/sjz/S2E/s2e/build/libs2e-debug/x86_64-s2e-softmmu/libs2e.so
set environment S2E_UNBUFFERED_STREAM=1
set environment S2E_MAX_PROCESSES=1