#!/usr/bin/env python3
"""Confirm MySQL screening reports. Default: plan only; --execute runs confirmation."""

import argparse
import csv
from datetime import datetime
from decimal import Decimal
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import signal
import subprocess
import sys
import traceback

sys.dont_write_bytecode = True
import generate_perf_report as reporting
import mysql_validation as validation

FINAL_MARKER = '<!-- generated by confirm_perf_reports.py -->'
save_json = validation.save_json
run_logged = validation.run_logged


def load_cases(args):
    root = args.root.resolve()
    report_dir = (args.report_dir or root / 'report').resolve()
    metadata = json.loads((report_dir / 'candidates.json').read_text(encoding='utf-8'))
    if metadata.get('schema_version') != 1:
        raise ValueError('Unsupported candidates.json schema; regenerate the screening report')
    source = Path(metadata['source']).resolve()
    candidates = metadata['candidates']
    selected = set(args.case or [])
    inputs = {}
    for candidate in candidates:
        identity = f'{candidate["commit"]}-{candidate["case"]}'
        if not reporting.REPORT_RE.fullmatch(identity + '.md') or identity in inputs:
            raise ValueError(f'Invalid/duplicate candidate: {identity}')
        if not selected or identity in selected:
            inputs[identity] = candidate
    if selected - inputs.keys():
        raise ValueError('Candidates not found: ' + ', '.join(sorted(selected - inputs.keys())))
    if args.expected_parent and len(inputs) != 1:
        raise ValueError('--expected-parent requires exactly one selected candidate')
    statuses = None
    if source != root:
        statuses = reporting.load_status(source.parent / 'status.tsv')
        if not statuses or not (source.parent / 'exit-status.txt').is_file():
            raise ValueError('Archived source has no completed run status')
    commits = list(dict.fromkeys(item['commit'] for item in inputs.values()))
    _, records, coverage = reporting.collect_reports(root, source, commits,
        args.threshold_percent / 100, statuses=statuses)
    fresh = {f'{item["commit"]}-{item["case"]}': item for item in records}
    coverage = {item['commit']: item for item in coverage}
    cases = []
    for identity, candidate in inputs.items():
        path = source / candidate['commit'] / candidate['case']
        symbolic = path / 'symbolic_testcase.txt'
        values = reporting.read_optional(symbolic).strip()
        item = dict(id=identity, commit=candidate['commit'], case=candidate['case'],
                    parent=candidate['parent'], report=str(report_dir / (identity + '.md')),
                    result_path=str(path / 'final-res.txt'), symbolic_file=str(symbolic),
                    symbolic_values=values,
                    symbolic_state='nonempty' if values else ('empty' if symbolic.is_file() else 'missing'),
                    action='manual_review', error='', query_count=None,
                    symbolic_slowdown_percent='', default_slowdown_percent='')
        try:
            if not Path(item['report']).is_file():
                raise ValueError('Candidate Markdown report is missing')
            current = fresh.get(identity)
            if current is None:
                raise ValueError('Result unavailable: ' + coverage[item['commit']]['reason'])
            if current['status'] == 'invalid':
                raise ValueError(current.get('reason', 'No valid execution mode'))
            if current['parent'] != item['parent']:
                raise ValueError('Parent changed since screening; regenerate the report')
            if args.expected_parent and item['parent'] != args.expected_parent:
                raise ValueError('Selected report does not match the supplied parent')
            for field in ('testcase', 'old_seconds', 'query_count'):
                if current.get(field) != candidate.get(field):
                    raise ValueError('Measurements changed since screening; regenerate the report')
            item['testcase'] = current['testcase']
            modes = current['modes']
            hits = {}
            for mode, label in ((reporting.SYMBOLIC, 'symbolic'), (reporting.DEFAULT, 'default')):
                data = modes[mode]
                previous = candidate['modes'][mode]
                if data.get('slowdown_percent') != previous.get('slowdown_percent'):
                    raise ValueError('Timings changed since screening; regenerate the report')
                item[label + '_slowdown_percent'] = data.get('slowdown_percent', '')
                hits[mode] = (data['status'] != 'invalid' and
                              Decimal(data['slowdown_percent']) >= args.threshold_percent)
            if values and hits[reporting.SYMBOLIC]:
                item['action'] = 'direct_report'
            elif any(hits.values()):
                item['query_count'] = validation.query_count(item['testcase'], args.mapping)
                item['action'] = 'benchmark'
            else:
                item['action'] = 'below_threshold'
        except (OSError, ValueError, KeyError) as error:
            item.update(action='manual_review', error=str(error))
        cases.append(item)
    return cases


def resolve_pair(repo, commit):
    def rev(expression):
        value = subprocess.check_output(['git', '-C', str(repo), 'rev-parse', '--verify', expression],
                                        text=True, stderr=subprocess.PIPE).strip()
        if not reporting.COMMIT_RE.fullmatch(value):
            raise ValueError(f'Invalid version: {expression}')
        return value
    return {'old': rev(f'{commit}^1'), 'new': rev(f'{commit}^{{commit}}')}


def build_version(repo, commit, builds, args):
    destination = builds / commit
    if (destination / 'built.json').is_file():
        return destination / 'build'
    destination.mkdir(exist_ok=True)
    source, build = destination / 'source', destination / 'build'
    if not source.exists():
        run_logged(['git', 'clone', '--no-hardlinks', '--no-checkout', str(repo), str(source)],
                   destination / 'clone.log', timeout=args.build_timeout)
    run_logged(['git', '-C', str(source), 'checkout', '--detach', commit],
               destination / 'checkout.log', timeout=args.build_timeout)
    environment = os.environ.copy()
    for key in ('CFLAGS', 'CPPFLAGS', 'CXXFLAGS', 'LDFLAGS', 'MAKEFLAGS', 'MFLAGS',
                'CC', 'CXX', 'CMAKE_BUILD_TYPE', 'CMAKE_GENERATOR'):
        environment.pop(key, None)
    command = ['cmake', '-S', str(source), '-B', str(build), '-G', 'Unix Makefiles',
               '-DCMAKE_BUILD_TYPE=RelWithDebInfo', f'-DCMAKE_C_COMPILER={args.cc}',
               f'-DCMAKE_CXX_COMPILER={args.cxx}', '-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O2 -g -DNDEBUG',
               '-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O2 -g -DNDEBUG', f'-DWITH_BOOST={args.boost_dir}']
    run_logged(command, destination / 'configure.log', timeout=args.build_timeout, env=environment)
    run_logged(['cmake', '--build', str(build), '--target', 'mysqld', 'mysql',
                '--parallel', str(args.jobs)], destination / 'build.log',
               timeout=args.build_timeout, env=environment)
    for executable in ('mysqld', 'mysql'):
        if not os.access(build / 'bin' / executable, os.X_OK):
            raise RuntimeError(f'Build did not produce {executable}: {build}')
    save_json(destination / 'built.json', dict(commit=commit, cc=args.cc, cxx=args.cxx,
                                              optimization='-O2 -g -DNDEBUG'))
    return build


def snapshot_file(source, destination):
    shutil.copyfile(source, destination)
    digest = hashlib.sha256()
    with destination.open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(chunk)
    save_json(destination.with_suffix(destination.suffix + '.json'),
              dict(source=str(source), sha256=digest.hexdigest()))
    return destination


def benchmark_case(case, folder, output, args):
    pair = resolve_pair(args.source_repo, case['commit'])
    if pair['old'] != case['parent']:
        raise ValueError('Report parent differs from the actual first parent')
    count = validation.query_count(case['testcase'], output / 'snapshots/sql-times.txt')
    if count != case['query_count']:
        raise ValueError('sql-times.txt changed after planning; restart confirmation')
    bins = {label: build_version(args.source_repo, commit, output / 'builds', args)
            for label, commit in pair.items()}
    measurements = {}
    for label in ('old', 'new'):
        destination = folder / label
        destination.mkdir()
        data = validation.extract_data(output / 'snapshots/tables.tar.gz', destination)
        measurements[label] = validation.measure(bins[label], case['testcase'], destination,
            data, output / 'snapshots/sql-times.txt', args.mysqlslap, args.timeout,
            args.startup_timeout, client=bins['new'] / 'bin/mysql')
    old, new = measurements['old'], measurements['new']
    if old['query_count'] != count or new['query_count'] != count:
        raise ValueError('Measured query counts do not match sql-times.txt x2')
    slowdown = (Decimal(new['seconds']) / Decimal(old['seconds']) - 1) * 100
    return dict(versions=pair, old=old, new=new, slowdown_percent=str(slowdown),
                status='benchmark_confirmed' if slowdown >= args.threshold_percent else 'not_reproduced')


def write_summary(output, results):
    with (output / 'summary.csv').open('w', newline='', encoding='utf-8') as stream:
        writer = csv.DictWriter(stream, fieldnames=['id', 'status', 'query_count',
                               'slowdown_percent', 'error'], extrasaction='ignore')
        writer.writeheader()
        writer.writerows(results)
    save_json(output / 'summary.json', results)


def format_final_report(content):
    def trim_result(match):
        lines = match['result'].splitlines(keepends=True)
        for index, line in enumerate(lines):
            if line.strip().lower().rstrip(':') in {'modified part', 'icount diff'}:
                return match['prefix'] + ''.join(lines[:index]).rstrip() + '\n' + match['closing']
        return match[0]
    return re.sub(r'(?P<prefix>^## Original Result\n\n(?P<fence>`{3,})text\n)'
                  r'(?P<result>.*?)(?P<closing>^(?P=fence)$)', trim_result, content,
                  flags=re.MULTILINE | re.DOTALL)


def publish_final_reports(output, results, final_dir, selected_only=False):
    accepted = {}
    for result in results:
        if result['status'] in {'direct_report', 'benchmark_confirmed'}:
            name = result['id'] + '.md'
            match = reporting.REPORT_RE.fullmatch(name)
            if not match:
                raise ValueError(f'Invalid report name: {name}')
            content = (output / 'reports' / name).read_text(encoding='utf-8')
            accepted[Path(match[1]) / name] = FINAL_MARKER + '\n' + format_final_report(content)
    owned = set()
    if final_dir.exists():
        for directory in final_dir.iterdir():
            if not reporting.COMMIT_RE.fullmatch(directory.name) or not directory.is_dir() or directory.is_symlink():
                continue
            for path in directory.glob('*.md'):
                if (reporting.REPORT_RE.fullmatch(path.name) and not path.is_symlink() and path.is_file()
                        and path.read_text(encoding='utf-8').startswith(FINAL_MARKER + '\n')):
                    owned.add(path.relative_to(final_dir))
    for relative in accepted:
        path = final_dir / relative
        if path.parent.is_symlink() or (path.parent.exists() and not path.parent.is_dir()):
            raise ValueError(f'Invalid final report directory: {path.parent}')
        if (path.exists() or path.is_symlink()) and relative not in owned:
            raise ValueError(f'Refusing to overwrite an unowned final report: {path}')
    final_dir.mkdir(parents=True, exist_ok=True)
    for relative, content in accepted.items():
        path = final_dir / relative
        path.parent.mkdir(exist_ok=True)
        path.write_text(content, encoding='utf-8')
    stale = owned - accepted.keys()
    if selected_only:
        selected = {result['id'] for result in results}
        stale = {relative for relative in stale if relative.stem in selected}
    for relative in stale:
        (final_dir / relative).unlink()
    for relative in {path.parent for path in stale}:
        directory = final_dir / relative
        if not any(directory.iterdir()):
            directory.rmdir()
    return len(accepted)


def execute(cases, args):
    if args.final_dir == args.report_dir:
        raise ValueError('Final reports must have a different directory from screening reports')
    benchmarks = any(case['action'] == 'benchmark' for case in cases)
    if benchmarks:
        for name in ('git', 'cmake', 'make', args.cc, args.cxx):
            if shutil.which(name) is None:
                raise ValueError(f'Required executable not found: {name}')
        for path in (args.source_repo, args.boost_dir, args.data_file, args.mapping):
            if not path.exists():
                raise ValueError(f'Missing dependency: {path}')
        if not os.access(args.mysqlslap, os.X_OK):
            raise ValueError(f'mysqlslap is unavailable: {args.mysqlslap}')
    output = (args.output_dir or args.root / 'report-confirmation' /
              datetime.now().strftime('%Y%m%d-%H%M%S-%f')).resolve()
    output.mkdir(parents=True, exist_ok=False)
    for name in ('builds', 'snapshots', 'cases', 'reports'):
        (output / name).mkdir()
    save_json(output / 'plan.json', cases)
    save_json(output / 'settings.json', {key: str(value) if isinstance(value, (Path, Decimal)) else value
                                       for key, value in vars(args).items()})
    if benchmarks:
        snapshot_file(args.mapping, output / 'snapshots/sql-times.txt')
        snapshot_file(args.data_file, output / 'snapshots/tables.tar.gz')
    results = []
    print(f'Confirmation output: {output}', flush=True)
    for case in cases:
        folder = output / 'cases' / case['id']
        folder.mkdir()
        result = dict(id=case['id'], status=case['action'], query_count=case['query_count'],
                      slowdown_percent='', error=case['error'],
                      symbolic_slowdown_percent=case['symbolic_slowdown_percent'],
                      default_slowdown_percent=case['default_slowdown_percent'])
        try:
            shutil.copyfile(case['report'], folder / 'original-report.md')
            for source in (case['symbolic_file'], case['result_path']):
                if Path(source).is_file():
                    shutil.copyfile(source, folder / Path(source).name)
            if case['action'] == 'direct_report':
                note = ('Retained by the Redis confirmation rule: nonempty symbolic values and a valid '
                        f'symbolic-mode slowdown of {case["symbolic_slowdown_percent"]}%, '
                        f'at least {args.threshold_percent}%. No additional benchmark was run.\n\n' +
                        reporting.fenced(case['symbolic_values']))
            elif case['action'] == 'benchmark':
                print(f'Benchmark: {case["id"]}, {case["query_count"]} queries per version (mapping x2)', flush=True)
                result.update(benchmark_case(case, folder, output, args))
                note = (f'Status: {result["status"]}. One round; one client; '
                        f'{case["query_count"]} queries per version (sql-times.txt x2).\n\n'
                        f'Old commit: `{result["versions"]["old"]}`; new commit: `{result["versions"]["new"]}`.\n\n'
                        f'Old batch: {result["old"]["seconds"]} seconds; new batch: {result["new"]["seconds"]} seconds.\n\n'
                        f'Slowdown: {Decimal(result["slowdown_percent"]):+.4f}%; threshold: {args.threshold_percent}%.\n\n'
                        'Formula: (new seconds / old seconds - 1) * 100. '
                        'Clean native builds, the same mysqlslap binary, SQL and initial data on both sides.')
            else:
                note = case['error'] or 'Neither valid mode meets the threshold.'
            if result['status'] in {'direct_report', 'benchmark_confirmed'}:
                content = Path(case['report']).read_text(encoding='utf-8')
                (output / 'reports' / (case['id'] + '.md')).write_text(
                    content + '\n## Confirmation\n\n' + note + '\n', encoding='utf-8')
            print(f'{case["id"]}: {result["status"]}', flush=True)
        except (KeyboardInterrupt, SystemExit):
            result.update(status='interrupted', error='Interrupted before confirmation finished')
            raise
        except (OSError, ValueError, RuntimeError, subprocess.SubprocessError, csv.Error) as error:
            result.update(status='error', error=str(error))
            (folder / 'error.log').write_text(traceback.format_exc(), encoding='utf-8')
            print(f'ERROR {case["id"]}: {error}', file=sys.stderr, flush=True)
        finally:
            results.append(result)
            save_json(folder / 'result.json', result)
            write_summary(output, results)
    retained = publish_final_reports(output, results, args.final_dir, selected_only=bool(args.case))
    save_json(output / 'completed.json', dict(retained=retained, final_dir=str(args.final_dir)))
    print(f'Retained reports: {retained}; final reports: {args.final_dir}')
    return 1 if any(item['status'] in {'error', 'manual_review'} for item in results) else 0


def parser():
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument('--root', type=Path, default=Path(__file__).resolve().parent)
    result.add_argument('--report-dir', type=Path)
    result.add_argument('--source-repo', type=Path)
    result.add_argument('--output-dir', type=Path, help='must not already exist')
    result.add_argument('--final-dir', type=Path)
    result.add_argument('--case', action='append', help='COMMIT-CASE; repeatable')
    result.add_argument('--expected-parent', help='check the parent for a single selected case')
    mode = result.add_mutually_exclusive_group()
    mode.add_argument('--execute', action='store_true')
    mode.add_argument('--dry-run', action='store_true', help='read-only plan (the default)')
    result.add_argument('--mapping', type=Path)
    result.add_argument('--data-file', type=Path, default=validation.DATA_FILE)
    result.add_argument('--mysqlslap', type=Path, default=validation.MYSQLSLAP)
    result.add_argument('--boost-dir', type=Path)
    result.add_argument('--jobs', type=validation.positive_int, default=24)
    result.add_argument('--cc', default='/usr/bin/cc')
    result.add_argument('--cxx', default='/usr/bin/c++')
    result.add_argument('--timeout', type=validation.positive_int, default=14400)
    result.add_argument('--build-timeout', type=validation.positive_int, default=14400)
    result.add_argument('--startup-timeout', type=validation.positive_int, default=120)
    result.add_argument('--threshold-percent', type=reporting.threshold_percent, default=Decimal('2'))
    return result


def main(argv=None):
    args = parser().parse_args(argv)
    args.root = args.root.resolve()
    for name, default in (('report_dir', args.root / 'report'), ('final_dir', args.root / 'report-final'),
                          ('source_repo', args.root / 'mysql-server'), ('mapping', args.root / 'sql-times.txt')):
        setattr(args, name, (getattr(args, name) or default).resolve())
    args.boost_dir = (args.boost_dir or args.source_repo / 'boost_1_77_0').resolve()
    args.data_file, args.mysqlslap = args.data_file.resolve(), args.mysqlslap.resolve()
    try:
        cases = load_cases(args)
        for case in cases:
            print(f'{case["action"]:14} {case["id"]} symbolic={case["symbolic_state"]} '
                  f'queries={case["query_count"] or "N/A"}' + (f' ({case["error"]})' if case['error'] else ''))
        counts = {action: sum(item['action'] == action for item in cases)
                  for action in ('direct_report', 'benchmark', 'below_threshold', 'manual_review')}
        print(f'Plan: {counts}; benchmark counts = sql-times.txt x2; threshold = {args.threshold_percent}%')
        if not args.execute:
            print('Plan only. No files changed and no build, MySQL or validation started. Use --execute to run.')
            return 1 if counts['manual_review'] else 0
        with (args.root / '.run_auto.lock').open('a') as lock:
            try:
                fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError as error:
                raise ValueError('Another MySQL run or confirmation is active') from error
            return execute(cases, args)
    except KeyboardInterrupt:
        print('Interrupted; owned child processes stopped, original results preserved.', file=sys.stderr)
        return 130
    except (OSError, ValueError, KeyError, subprocess.SubprocessError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(143))
    sys.exit(main())
