#!/usr/bin/env python3
"""Report MySQL slowdowns from existing results; never run experiments.

Usage: python3 generate_perf_report.py [--threshold-percent 2] [--dry-run]
Only commits listed in root/commit-tmp.txt are scanned. Each report is named
<commit>-<case>.md. Ratios in final-res.txt are fractions, not percentages.
Use --run-dir for an existing full-*/results or replay-*/results archive.
"""

import argparse
import csv
from decimal import Decimal, InvalidOperation
import hashlib
import io
import json
from pathlib import Path
import re
import subprocess
import sys


DEFAULT_ROOT = Path(__file__).resolve().parent
MARKER = '<!-- generated by generate_perf_report.py -->'
COMMIT_RE = re.compile(r'[0-9a-fA-F]{40}')
REPORT_RE = re.compile(r'([0-9a-f]{40})-([0-9]+)\.md')
SYMBOLIC = 'New version (symbolic path)'
DEFAULT = 'New version (default execution)'
OLD = 'Old version'
SYMBOLIC_CHANGE = 'New vs. old (symbolic path)'
DEFAULT_CHANGE = 'New vs. old (default execution)'
LABELS = (SYMBOLIC, DEFAULT, OLD, SYMBOLIC_CHANGE, DEFAULT_CHANGE)
LEGACY_LABELS = {
    '\u65b0\u7248\u672c\u6cbf\u7b26\u53f7\u6267\u884c': SYMBOLIC,
    '\u65b0\u7248\u672c\u9ed8\u8ba4\u6267\u884c': DEFAULT,
    '\u65e7\u7248\u672c': OLD,
    '\u65b0\u65e7\u7248\u672c\u6bd4\u8f83\uff08\u6cbf\u7b26\u53f7\u6267\u884c\uff09': SYMBOLIC_CHANGE,
    '\u65b0\u65e7\u7248\u672c\u6bd4\u8f83\uff08\u9ed8\u8ba4\u6267\u884c\uff09': DEFAULT_CHANGE,
}
MODES = ((SYMBOLIC, SYMBOLIC_CHANGE), (DEFAULT, DEFAULT_CHANGE))
BENCHMARKS = {SYMBOLIC: 'real-execute-res.txt', DEFAULT: 'real-execute-res-pure.txt',
              OLD: 'real-execute-res-old.txt'}
FAILURES = {
    SYMBOLIC: ('\u65b0\u7248\u672c\u7b26\u53f7\u6267\u884c\u63d2\u6869\u540e\u7f16\u8bd1\u5931\u8d25',
               '\u65b0\u7248\u672c\u65e0\u5360\u6bd4\u771f\u5b9e\u6267\u884c\u63d2\u6869\u540e\u7f16\u8bd1\u5931\u8d25'),
    DEFAULT: ('\u65b0\u7248\u672c\u5b8c\u5168\u771f\u5b9e\u6267\u884c\u63d2\u6869\u540e\u7f16\u8bd1\u5931\u8d25',),
    OLD: ('\u65e7\u7248\u672c\u65e0\u5360\u6bd4\u771f\u5b9e\u6267\u884c\u63d2\u6869\u540e\u7f16\u8bd1\u5931\u8d25',),
}


def load_commits(path):
    commits = []
    for value in path.read_text(encoding='utf-8-sig').splitlines():
        value = value.strip().lower()
        if not value or value.startswith('#'):
            continue
        if not COMMIT_RE.fullmatch(value) or value in commits:
            raise ValueError(f'Invalid/duplicate commit in {path}: {value}')
        commits.append(value)
    if not commits:
        raise ValueError(f'No full commit hashes found in {path}')
    return commits


def read_optional(path):
    return path.read_text(encoding='utf-8') if path.is_file() else ''


def load_status(path):
    if not path.is_file():
        return {}
    with path.open(encoding='utf-8', newline='') as stream:
        rows = list(csv.DictReader(stream, delimiter='\t'))
    result = {}
    for row in rows:
        commit, parent = row.get('commit', ''), row.get('parent', '')
        if not COMMIT_RE.fullmatch(commit) or not COMMIT_RE.fullmatch(parent) or commit in result:
            raise ValueError(f'Invalid commit/parent in {path}')
        int(row['exit_status'])
        result[commit] = row
    return result


def parse_result(path):
    content = path.read_text(encoding='utf-8')
    lines = [line.strip() for line in content.splitlines() if line.strip()]
    values = {}
    for index, line in enumerate(lines):
        line = LEGACY_LABELS.get(line, line)
        if line not in LABELS:
            continue
        if line in values:
            raise ValueError(f'duplicate field: {line}')
        if index + 1 == len(lines):
            raise ValueError(f'missing value: {line}')
        try:
            value = Decimal(lines[index + 1])
        except InvalidOperation as error:
            raise ValueError(f'invalid number for {line}') from error
        if not value.is_finite():
            raise ValueError(f'non-finite number for {line}')
        values[line] = value
    missing = [label for label in LABELS if label not in values]
    if missing:
        raise ValueError('incomplete end-to-end results: ' + ', '.join(missing))
    for label in (SYMBOLIC, DEFAULT, OLD):
        if values[label] <= 0:
            raise ValueError(f'non-positive execution time: {label}')
    for mode, change in MODES:
        calculated = (values[mode] - values[OLD]) / values[OLD]
        if abs(calculated - values[change]) > Decimal('0.000001'):
            raise ValueError(f'ratio disagrees with execution times: {change}')
    return values, content


def benchmark(path):
    content = read_optional(path)
    if re.search(r'\[ERROR\]|^ERROR\b|mysqlslap:.*(?:error|failed)', content, re.I | re.M):
        raise ValueError(f'Execution error in {path.name}')
    patterns = (r'Average number of seconds to run all queries:\s*(\S+)\s+seconds',
                r'Average number of queries per client:\s*(\S+)',
                r'Number of clients running queries:\s*(\S+)')
    values = []
    for pattern in patterns:
        matches = re.findall(pattern, content)
        if len(matches) != 1:
            raise ValueError(f'Missing/multiple benchmark summaries in {path.name}')
        try:
            value = Decimal(matches[0])
        except InvalidOperation as error:
            raise ValueError(f'Invalid benchmark number in {path.name}') from error
        if not value.is_finite() or value <= 0:
            raise ValueError(f'Non-positive/non-finite benchmark number in {path.name}')
        values.append(value)
    seconds, queries, clients = values
    if queries != int(queries) or clients != 1:
        raise ValueError(f'Invalid query count or concurrency in {path.name}')
    return seconds, int(queries)


def load_case_commands(directory):
    path = directory / 'call_analyse2.txt'
    if not path.is_file():
        return {}
    groups = {True: [], False: []}
    is_null = False
    for block in re.split(r'\n\s*\n', path.read_text(encoding='utf-8').strip()):
        marker = block.strip().upper()
        if marker in {'BEGIN NULL', 'END NULL'}:
            is_null = marker == 'BEGIN NULL'
            continue
        for line in block.splitlines():
            line = line.strip()
            if line.startswith('testcase:'):
                command = line[len('testcase:'):].strip()
                if command and command != 'no testcase':
                    groups[is_null].append(command)
                break
    # The runner handles NULL blocks first.
    return {str(index): command for index, command in
            enumerate(groups[True] + groups[False], 1)}


def read_case_command(path, fallback):
    return read_optional(path.parent / 'testcase.txt').strip() or fallback.get(path.parent.name, '')


def percent(ratio):
    return f'{ratio * 100:+.4f}%'


def fenced(content):
    longest = max((len(match) for match in re.findall(r'`+', content)), default=0)
    fence = '`' * max(3, longest + 1)
    return f'{fence}text\n{content.rstrip()}\n{fence}'


def render_report(record, values, content, threshold):
    commit, case, command = record['commit'], record['case'], record['testcase']
    path = Path(record['result_path'])
    hits = [mode for mode, data in record['modes'].items() if data['status'] == 'candidate']
    lines = [
        MARKER, f'# Potential Performance Regression: {commit} / {case}', '',
        f'- Commit: `{commit}`', f'- Case: `{case}`',
        f'- Parent: `{record["parent"]}`',
        f'- Source: `{path}`',
        f'- Queries per version: {record["query_count"]}',
        f'- Planned validation queries: {record["query_count"] * 2} (2x; verify sql-times.txt before validation)',
        f'- Threshold: slowdown >= {threshold * 100:g}%',
        '- Flagged modes: ' + ', '.join(hits), '',
        '| Execution mode | New batch (seconds) | Old batch (seconds) | Slowdown | Status |',
        '| --- | ---: | ---: | ---: | --- |',
    ]
    for mode, change in MODES:
        data = record['modes'][mode]
        lines.append(
            f'| {mode} | {data.get("new_seconds", "N/A")} | {record["old_seconds"]} | '
            f'{percent(values[change])} | {data["status"]} |')
    lines += ['', 'Positive percentages mean slower than the old version.',
              'These are screening candidates, not confirmed regressions. Validation has not run.',
              'Times above come from mysqlslap batch seconds. The legacy final-res.txt divides',
              'these by 10; ratios are checked against both sources.']

    if command:
        lines += ['', '## Test Command', '', fenced(command)]
    else:
        lines += ['', 'Test command unavailable.']

    if SYMBOLIC in hits:
        symbolic_path = path.parent / 'symbolic_testcase.txt'
        lines += ['', '## Symbolic Values', '', f'Source: `{symbolic_path}`', '']
        if not symbolic_path.is_file():
            lines.append('symbolic_testcase.txt is missing. No symbolic values are available; '
                         'the symbolic-mode timing alone does not establish a symbolic input.')
        else:
            symbolic = symbolic_path.read_text(encoding='utf-8').strip()
            lines.append(fenced(symbolic) if symbolic else
                         'symbolic_testcase.txt is empty. No symbolic values were generated; '
                         'the symbolic-mode timing alone does not establish a symbolic input.')
    warnings = record['warnings'] + [f'{mode}: {data["reason"]}'
        for mode, data in record['modes'].items() if 'reason' in data]
    lines += ['', '## Diagnostics', '', fenced('\n'.join(warnings)) if warnings else
              'No screening checks failed.', '', '## Original Result', '', fenced(content), '']
    return '\n'.join(lines)


def collect_reports(root, source, commits, threshold, statuses=None, skipped=(), run_dir=None):
    reports, records, coverage = {}, [], []
    for commit in commits:
        directory = source / commit
        row = dict(commit=commit, status='scanned', reason='', cases=0)
        coverage.append(row)
        status = (statuses.get(commit) if statuses is not None else
                  load_status(directory / 'run-status.tsv').get(commit))
        if commit in skipped:
            row.update(status='skipped', reason='Outside run selection')
            continue
        if statuses is not None and status is None:
            row.update(status='unfinished', reason='No completed status row')
            continue
        if status and int(status['exit_status']) != 0:
            row.update(status='failed', reason=f'Exit status {status["exit_status"]}')
            continue
        if not directory.is_dir():
            row.update(status='missing', reason='Result directory absent')
            continue
        if run_dir and source == root:
            local = load_status(directory / 'run-status.tsv').get(commit, {})
            if not local.get('run_dir') or Path(local['run_dir']).resolve() != run_dir:
                row.update(status='replaced', reason='Root results belong to a different run')
                continue
        commands = load_case_commands(directory)
        cases = sorted(set(commands) | {item.name for item in directory.iterdir()
                        if item.is_dir() and re.fullmatch(r'[1-9][0-9]*', item.name)}, key=int)
        row['cases'] = len(cases)
        if not cases:
            row.update(status='no_cases', reason='No runnable testcases/results saved')
            continue
        if status:
            parent = status['parent']
        else:
            process = subprocess.run(['git', '-C', str(root / 'mysql-server'), 'rev-parse',
                                      f'{commit}^1'], capture_output=True, text=True)
            parent = process.stdout.strip()
            if process.returncode or not COMMIT_RE.fullmatch(parent):
                row.update(status='invalid', reason='Cannot resolve actual first parent')
                continue
        for case in cases:
            path = directory / case / 'final-res.txt'
            record = dict(commit=commit, parent=parent, case=case, result_path=str(path),
                          testcase=read_case_command(path, commands), status='invalid',
                          validation_status='not_run', modes={}, warnings=[])
            records.append(record)
            old_dir = source / f'{parent}-old' / case
            compile_new = read_optional(path.parent / 'compile.txt')
            compile_old = read_optional(old_dir / 'compile.txt')
            record['warnings'] = [line for line in (compile_new + '\n' + compile_old).splitlines()
                                  if line.strip()]
            try:
                values, content = parse_result(path)
                if not record['testcase'] or record['testcase'] == 'no testcase':
                    raise ValueError('Missing testcase SQL')
                old_seconds, queries = benchmark(path.parent / BENCHMARKS[OLD])
                if any(message in compile_old for message in FAILURES[OLD]):
                    raise ValueError('Old native compilation failed')
            except (ValueError, OSError) as error:
                record['reason'] = str(error)
                continue
            record.update(old_seconds=str(old_seconds), query_count=queries,
                          validation_query_count=queries * 2,
                          symbolic_testcase=str(path.parent / 'symbolic_testcase.txt'),
                          old_result_dir=str(old_dir))
            for mode, change in MODES:
                data = dict(status='invalid', slowdown_percent=str(values[change] * 100))
                record['modes'][mode] = data
                try:
                    if any(message in compile_new for message in FAILURES[mode]):
                        raise ValueError('Compilation failed; see compile.txt')
                    seconds, count = benchmark(path.parent / BENCHMARKS[mode])
                    if count != queries:
                        raise ValueError(f'Query counts differ: new={count}, old={queries}')
                    ratio = (seconds - old_seconds) / old_seconds
                    if abs(ratio - values[change]) > Decimal('0.000001'):
                        raise ValueError('Raw timings disagree with final-res.txt ratio')
                    data.update(status='candidate' if ratio >= threshold else 'below_threshold',
                                new_seconds=str(seconds))
                except (ValueError, OSError) as error:
                    data['reason'] = str(error)
            symbolic = read_optional(path.parent / 'symbolic_testcase.txt')
            if not symbolic.strip():
                record['warnings'].append('No saved symbolic values; symbolic input is unverified.')
            modified = re.search(r'Average modified part:\s*(\S+)', content)
            total = re.search(r'Average end to end:\s*(\S+)', content)
            if modified and total:
                try:
                    m, t = Decimal(modified[1]), Decimal(total[1])
                    if not m.is_finite() or not t.is_finite() or not 0 <= m <= t:
                        record['warnings'].append('Invalid modified-part metric; not used for screening.')
                except InvalidOperation:
                    record['warnings'].append('Invalid modified-part metric; not used for screening.')
            states = [data['status'] for data in record['modes'].values()]
            record['status'] = ('candidate' if 'candidate' in states else
                                'below_threshold' if 'below_threshold' in states else 'invalid')
            if record['status'] == 'candidate':
                reports[f'{commit}-{case}.md'] = render_report(record, values, content, threshold)
    return reports, records, coverage


def csv_text(rows, fields):
    stream = io.StringIO(newline='')
    writer = csv.DictWriter(stream, fieldnames=fields)
    writer.writeheader()
    writer.writerows(rows)
    return stream.getvalue()


def add_summary(reports, records, coverage, source, threshold):
    candidates = [r for r in records if r['status'] == 'candidate']
    reports['candidates.json'] = json.dumps(dict(schema_version=1, source=str(source),
        threshold_percent=str(threshold * 100), validation_status='not_run', candidates=candidates),
        ensure_ascii=False, indent=2) + '\n'
    rows = []
    for r in records:
        for mode, _ in MODES:
            data = r['modes'].get(mode, {})
            rows.append(dict(commit=r['commit'], parent=r['parent'], case=r['case'], mode=mode,
                status=data.get('status', 'invalid'), slowdown_percent=data.get('slowdown_percent', ''),
                query_count=r.get('query_count', ''), testcase=r['testcase'],
                reason=data.get('reason', r.get('reason', '')), warnings=' | '.join(r['warnings']),
                result_path=r['result_path']))
    reports['cases.csv'] = csv_text(rows, ['commit', 'parent', 'case', 'mode', 'status',
        'slowdown_percent', 'query_count', 'testcase', 'reason', 'warnings', 'result_path'])
    reports['commits.csv'] = csv_text(coverage, ['commit', 'status', 'reason', 'cases'])
    lines = [MARKER, '# MySQL Performance Screening', '', f'- Source: `{source}`',
        f'- Threshold: slowdown >= {threshold * 100:g}% in either valid mode',
        f'- Listed commits: {len(coverage)}; testcases checked: {len(records)}',
        f'- Candidate testcases: {len(candidates)}; candidate commits: {len({r["commit"] for r in candidates})}',
        f'- Invalid/incomplete testcases: {sum(r["status"] == "invalid" for r in records)}',
        '- These are candidates, not confirmed regressions. Validation has not run.', '',
        '[All testcase checks](cases.csv) | [Commit coverage](commits.csv) | [Validation inputs](candidates.json)', '',
        'Times and counts come from mysqlslap logs. Missing/non-finite data, inconsistent ratios,',
        'unequal query counts and compilation failures are excluded. Symbolic compilation',
        'failure does not invalidate a successful default-mode measurement.',
        'Modified-part and instruction counts are not used as slowdown thresholds.', '',
        '| Commit | Case | Symbolic slowdown | Default slowdown | Report |',
        '| --- | ---: | ---: | ---: | --- |']
    for r in candidates:
        values = [f'{Decimal(r["modes"][mode]["slowdown_percent"]):+.4f}%'
                  if r['modes'][mode]['status'] != 'invalid' else 'invalid' for mode, _ in MODES]
        name = f'{r["commit"]}-{r["case"]}.md'
        lines.append(f'| `{r["commit"][:12]}` | {r["case"]} | {values[0]} | {values[1]} | [details]({name}) |')
    if not candidates:
        lines += ['', 'No valid measured slowdown reached the threshold.']
    reports['README.md'] = '\n'.join(lines) + '\n'
    return candidates


def write_reports(output, reports):
    manifest = output / '.generated-files.json'
    owned = {}
    if manifest.is_symlink():
        raise ValueError(f'Report manifest is a symlink: {manifest}')
    if manifest.exists():
        metadata = json.loads(manifest.read_text(encoding='utf-8'))
        if metadata.get('generator') != MARKER:
            raise ValueError(f'Unrecognized manifest: {manifest}')
        owned = metadata['files']
    for name in set(owned) | set(reports):
        if Path(name).name != name or name in ('.', '..', manifest.name):
            raise ValueError('Invalid report filename')
        path = output / name
        if path.is_symlink() or (path.exists() and (name not in owned or
                hashlib.sha256(path.read_bytes()).hexdigest() != owned[name])):
            raise ValueError(f'Refusing to overwrite an unowned/edited report: {path}')
    output.mkdir(parents=True, exist_ok=True)
    for name, content in reports.items():
        (output / name).write_text(content, encoding='utf-8')
    for name in owned.keys() - reports.keys():
        (output / name).unlink(missing_ok=True)
    manifest.write_text(json.dumps(dict(generator=MARKER, files={
        name: hashlib.sha256(content.encode('utf-8')).hexdigest()
        for name, content in reports.items()}), indent=2) + '\n', encoding='utf-8')


def threshold_percent(value):
    try:
        number = Decimal(value)
    except InvalidOperation as error:
        raise argparse.ArgumentTypeError('threshold must be a number') from error
    if not number.is_finite() or number <= 0:
        raise argparse.ArgumentTypeError('threshold must be finite and positive')
    return number


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=DEFAULT_ROOT)
    parser.add_argument('--output-dir', type=Path,
                        help='default: ROOT/report; only generated reports are refreshed')
    parser.add_argument('--run-dir', type=Path, help='Read a specific completed run, including old archives')
    parser.add_argument('--commit-file', type=Path, help='Override the commit list')
    parser.add_argument('--threshold-percent', type=threshold_percent, default=Decimal('2'),
                        help='inclusive slowdown percentage, default: 2')
    parser.add_argument('--dry-run', action='store_true', help='scan without writing reports')
    args = parser.parse_args(argv)
    root = args.root.resolve()
    output = (args.output_dir or root / 'report').resolve()
    try:
        source, statuses, skipped, run = root, None, set(), None
        commit_file = args.commit_file or root / 'commit-tmp.txt'
        if args.run_dir:
            run = args.run_dir.resolve()
            if not (run / 'exit-status.txt').is_file():
                raise ValueError(f'Run has not finished: {run}')
            source = run / 'results'
            if not source.is_dir():
                stored_root = read_optional(run / 'results-root.txt').strip()
                if not stored_root:
                    raise ValueError(f'Result location is missing in {run}')
                source = Path(stored_root).resolve()
            if not args.commit_file:
                commit_file = (run / 'selected-commits.txt' if (run / 'selected-commits.txt').is_file()
                               else run / 'commits.txt')
            statuses = load_status(run / 'status.tsv')
            if not statuses:
                raise ValueError(f'Missing status.tsv in {run}')
            skip_path = run / 'skipped-by-selection.tsv'
            if skip_path.is_file():
                with skip_path.open(encoding='utf-8', newline='') as stream:
                    skipped = {r['commit'] for r in csv.DictReader(stream, delimiter='\t')}
        commits = load_commits(commit_file)
        if not any((source / commit).is_dir() for commit in commits):
            raise ValueError(f'No commit results in {source}; use --run-dir for an archive')
        threshold = args.threshold_percent / 100
        reports, records, coverage = collect_reports(root, source, commits, threshold, statuses, skipped, run)
        candidates = add_summary(reports, records, coverage, source, threshold)
        if not args.dry_run:
            write_reports(output, reports)
    except (OSError, ValueError, KeyError, csv.Error) as error:
        parser.exit(1, f'ERROR: {error}\n')
    print(f'Commits: {len(commits)}; cases: {len(records)}; candidate cases: {len(candidates)}')
    print(f'{"Would write" if args.dry_run else "Report"}: {output / "README.md"}')
    print('No experiments or validation were launched.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
