#!/usr/bin/env python3
"""Confirm existing reports. Default: read-only plan; --execute runs benchmarks."""

import argparse
import csv
from datetime import datetime
from decimal import Decimal
import hashlib
import io
import json
import math
import os
from pathlib import Path
import re
import shlex
import shutil
import signal
import socket
import subprocess
import sys
import time
import traceback

sys.dont_write_bytecode = True
import generate_perf_report as reporting


FINAL_MARKER = '<!-- generated by confirm_perf_reports.py -->'
NONREPEATABLE = {
    'AUTH', 'SELECT', 'HELLO', 'RESET', 'QUIT', 'SHUTDOWN', 'MONITOR',
    'MULTI', 'EXEC', 'DISCARD', 'WATCH', 'UNWATCH', 'SUBSCRIBE', 'PSUBSCRIBE',
    'SSUBSCRIBE', 'UNSUBSCRIBE', 'PUNSUBSCRIBE', 'SUNSUBSCRIBE',
    'BLPOP', 'BRPOP', 'BRPOPLPUSH', 'BLMOVE', 'BLMPOP', 'BZPOPMIN', 'BZPOPMAX',
    'BZMPOP', 'RENAME', 'RENAMENX', 'BGREWRITEAOF', 'BGSAVE', 'SAVE',
    'REPLCONF', 'REPLICAOF', 'SLAVEOF', 'SYNC', 'PSYNC', 'FAILOVER',
    'MODULE', 'CONFIG', 'ACL', 'CLUSTER', 'DEBUG',
}
CONTROLLED_SERVER_OPTIONS = {
    '--dir', '--dbfilename', '--save', '--appendonly', '--pidfile', '--port',
    '--bind', '--daemonize', '--logfile', '--unixsocket', '--protected-mode',
}


def save_json(path, value):
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def positive_int(value):
    number = int(value)
    if number <= 0:
        raise argparse.ArgumentTypeError('must be positive')
    return number


def command_arguments(text):
    args = shlex.split(text)
    if args and Path(args[0]).name == 'redis-cli':
        args = args[1:]
    if not args or not args[0] or args[0].startswith('-') or Path(args[0]).name == 'redis-server':
        raise ValueError('a Redis command is required, not a redis-cli option or server startup')
    name = args[0].upper()
    if name in NONREPEATABLE or (name in {'XREAD', 'XREADGROUP'} and
                                 'BLOCK' in [arg.upper() for arg in args[1:]]):
        raise ValueError(f'{name} needs manual verification; it is not a repeatable benchmark command')
    if any(arg in {'|', '||', '&&', ';', '>', '>>', '<'} for arg in args):
        raise ValueError('shell operators are not supported in benchmark commands')
    return args


def server_inputs(directory, case, data_override=None, empty_db=False):
    source = None
    for suffix in ('-2', '-1', ''):
        candidate = directory / 'src' / f'{case}{suffix}' / 'bin/get_redis_2.txt'
        if candidate.is_file() and candidate.read_text(encoding='utf-8').strip():
            source = candidate
            break
    if source is None:
        if data_override is not None or empty_db:
            return [], data_override, None
        raise ValueError('no saved server command; specify --data-file or --empty-db')
    args = shlex.split(source.read_text(encoding='utf-8').strip().splitlines()[-1])
    if not args or Path(args[0]).name != 'redis-server':
        raise ValueError(f'unrecognized server command in {source}')
    options = {}
    index = 1
    while index < len(args):
        key = args[index]
        if not key.startswith('--'):
            raise ValueError(f'server config files or positional arguments need manual review: {key}')
        index += 1
        values = []
        while index < len(args) and not args[index].startswith('--'):
            values.append(args[index])
            index += 1
        if not values or key in options:
            raise ValueError(f'missing value or repeated server option: {key}')
        options[key] = values
    if (options.get('--cluster-enabled', ['no']) != ['no'] or
            '--replicaof' in options or '--slaveof' in options):
        raise ValueError('cluster/replica startup needs manual verification')
    extra = []
    for key, values in options.items():
        if key in CONTROLLED_SERVER_OPTIONS:
            continue
        if key == '--loadmodule':
            module = Path(values[0])
            if not module.is_absolute():
                module = source.parent / module
            values = [str(module.resolve()), *values[1:]]
        extra += [key, *values]
    data = None
    if not empty_db:
        if data_override is not None:
            data = data_override
        else:
            data_dir = Path(options.get('--dir', [str(source.parent)])[0])
            if not data_dir.is_absolute():
                data_dir = source.parent / data_dir
            data = data_dir / options.get('--dbfilename', ['dump.rdb'])[0]
    return extra, data, str(source)


def load_cases(args):
    root = args.root.resolve()
    report_dir = (args.report_dir or root / 'report').resolve()
    if not report_dir.is_dir():
        raise ValueError(f'report directory does not exist: {report_dir}')
    selected = set(args.case or [])
    cases = []
    for path in sorted(report_dir.glob('*.md')):
        match = reporting.REPORT_RE.fullmatch(path.name)
        if not match or (selected and path.stem not in selected):
            continue
        commit, case = match.groups()
        directory = root / f'redis-{commit}'
        symbolic = directory / case / 'symbolic_testcase.txt'
        values = symbolic.read_text(encoding='utf-8').strip() if symbolic.is_file() else ''
        item = dict(id=path.stem, commit=commit, case=case, report=str(path),
                    symbolic_file=str(symbolic), symbolic_values=values,
                    symbolic_state='nonempty' if values else ('empty' if symbolic.is_file() else 'missing'),
                    action='below_threshold', error='',
                    symbolic_slowdown_percent='', default_slowdown_percent='')
        try:
            timings, _ = reporting.parse_result(directory / case / 'final-res.txt')
            symbolic_percent = timings[reporting.SYMBOLIC_CHANGE] * 100
            default_percent = timings[reporting.DEFAULT_CHANGE] * 100
            item.update(symbolic_slowdown_percent=str(symbolic_percent),
                        default_slowdown_percent=str(default_percent))
            if values and symbolic_percent >= args.threshold_percent:
                item['action'] = 'direct_report'
            elif (default_percent >= args.threshold_percent or
                  (not values and symbolic_percent >= args.threshold_percent)):
                item['action'] = 'benchmark'
            if item['action'] == 'benchmark':
                command = reporting.read_case_command(directory / case / 'final-res.txt',
                                                       reporting.load_case_commands(directory))
                item['command'] = command
                item['argv'] = command_arguments(command)
                extra, data, source = server_inputs(directory, case, args.data_file, args.empty_db)
                if data is not None and not data.is_file():
                    raise ValueError(f'initial RDB is missing: {data}; specify --data-file or --empty-db')
                item.update(server_extra=extra, data_file=str(data.resolve()) if data else None,
                            server_command_file=source)
        except (ValueError, OSError) as error:
            item['error'] = str(error)
            item['action'] = 'manual_review'
        cases.append(item)
    absent = selected - {case['id'] for case in cases}
    if absent:
        raise ValueError('reports not found: ' + ', '.join(sorted(absent)))
    if not cases:
        raise ValueError(f'no commit-case reports found in {report_dir}')
    return cases


def stop_process(process):
    if process.poll() is not None:
        return
    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        return
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        os.killpg(process.pid, signal.SIGKILL)
        process.wait()


def run_logged(command, log, cwd=None, timeout=3600, env=None, stderr=None):
    save_json(log.with_suffix(log.suffix + '.command.json'), command)
    with log.open('w', encoding='utf-8') as output:
        error_stream = stderr.open('w', encoding='utf-8') if stderr else None
        try:
            process = subprocess.Popen(command, cwd=cwd, stdout=output,
                                       stderr=error_stream or subprocess.STDOUT,
                                       env=env, start_new_session=True)
            try:
                code = process.wait(timeout=timeout)
            finally:
                stop_process(process)
        finally:
            if error_stream:
                error_stream.close()
    if code != 0:
        raise RuntimeError(f'command exited with {code}; see {log}')


def resolve_pair(repo, commit):
    def rev(expression):
        return subprocess.check_output(['git', '-C', str(repo), 'rev-parse', '--verify', expression],
                                       text=True, stderr=subprocess.PIPE).strip()
    return {'old': rev(f'{commit}^1'), 'new': rev(f'{commit}^{{commit}}')}


def build_version(repo, commit, builds, args):
    destination = builds / commit
    if (destination / 'built.json').is_file():
        return destination / 'source/src'
    destination.mkdir()
    source = destination / 'source'
    # A local clone copies the repository without copying dirty/instrumented worktree files.
    run_logged(['git', 'clone', '--no-hardlinks', '--no-checkout', str(repo), str(source)],
               destination / 'clone.log', timeout=args.timeout)
    run_logged(['git', '-C', str(source), 'checkout', '--detach', commit],
               destination / 'checkout.log', timeout=args.timeout)
    environment = os.environ.copy()
    for key in ('CFLAGS', 'CPPFLAGS', 'CXXFLAGS', 'LDFLAGS', 'REDIS_CFLAGS',
                'REDIS_LDFLAGS', 'MAKEFLAGS', 'MFLAGS'):
        environment.pop(key, None)
    run_logged(['make', f'-j{args.jobs}', f'CC={args.cc}', 'OPTIMIZATION=-O3'],
               destination / 'build.log', cwd=source, timeout=args.timeout, env=environment)
    for executable in ('redis-server', 'redis-cli', 'redis-benchmark'):
        if not os.access(source / 'src' / executable, os.X_OK):
            raise RuntimeError(f'build did not produce {executable}: {source}')
    save_json(destination / 'built.json', dict(commit=commit, cc=args.cc, optimization='-O3'))
    return source / 'src'


def snapshot_data(source, snapshots):
    if source is None:
        return None
    key = hashlib.sha256(str(source).encode()).hexdigest()[:16]
    snapshot = snapshots / f'{key}.rdb'
    if not snapshot.exists():
        shutil.copyfile(source, snapshot)
        digest = hashlib.sha256()
        with snapshot.open('rb') as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b''):
                digest.update(chunk)
        save_json(snapshot.with_suffix('.json'), dict(source=str(source), sha256=digest.hexdigest()))
    return snapshot


def parse_benchmark(output, errors=''):
    if any(word in errors.lower() for word in ('error', 'wrongtype', 'noauth', 'clusterdown')):
        raise ValueError('benchmark reported an error; inspect benchmark.stderr.log')
    rows = []
    for row in csv.reader(io.StringIO(output), strict=True):
        if not row or row[0].lower() == 'test':
            continue
        if len(row) != 8:
            raise ValueError(f'expected 8 benchmark CSV columns, got {len(row)}')
        try:
            numbers = [float(value) for value in row[1:]]
        except ValueError as error:
            raise ValueError('invalid benchmark CSV number') from error
        if not all(math.isfinite(value) and value >= 0 for value in numbers) or numbers[0] <= 0:
            raise ValueError('benchmark returned invalid throughput/latency')
        rows.append(dict(command=row[0], rps=row[1], average_latency_ms=row[2],
                         p50_latency_ms=row[4], p95_latency_ms=row[5], p99_latency_ms=row[6]))
    if len(rows) != 1:
        raise ValueError(f'expected exactly one benchmark result, got {len(rows)}')
    return rows[0]


def wait_ready(process, cli, port, deadline):
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise RuntimeError('redis-server exited during startup; inspect server.log')
        prefix = [str(cli), '-h', '127.0.0.1', '-p', str(port), '--raw']
        try:
            ping = subprocess.run(prefix + ['PING'], capture_output=True, text=True, timeout=2)
            if ping.returncode == 0 and ping.stdout.strip() == 'PONG':
                info = subprocess.run(prefix + ['INFO', 'server'], capture_output=True,
                                      text=True, timeout=2, check=True)
                fields = dict(line.split(':', 1) for line in info.stdout.splitlines() if ':' in line)
                if fields.get('process_id') != str(process.pid):
                    raise RuntimeError('port belongs to a different Redis process')
                return
        except subprocess.TimeoutExpired:
            pass
        time.sleep(0.2)
    raise TimeoutError('Redis startup timed out; inspect server.log')


def measure(bin_dir, client_dir, case, destination, snapshot, args):
    destination.mkdir()
    data_dir = destination / 'data'
    data_dir.mkdir()
    if snapshot is not None:
        shutil.copyfile(snapshot, data_dir / 'dump.rdb')
    with socket.socket() as probe:
        probe.bind(('127.0.0.1', args.port))
    server = ['taskset', '-c', str(args.server_cpu), str(bin_dir / 'redis-server'),
              *case['server_extra'], '--bind', '127.0.0.1', '--port', str(args.port),
              '--protected-mode', 'yes', '--daemonize', 'no', '--save', '', '--appendonly', 'no',
              '--dir', str(data_dir), '--dbfilename', 'dump.rdb', '--pidfile', str(destination / 'redis.pid'),
              '--logfile', '', '--unixsocket', '']
    save_json(destination / 'server-command.json', server)
    with (destination / 'server.log').open('w') as stream:
        process = subprocess.Popen(server, stdout=stream, stderr=subprocess.STDOUT,
                                   cwd=destination, start_new_session=True)
        try:
            wait_ready(process, client_dir / 'redis-cli', args.port,
                       time.monotonic() + args.startup_timeout)
            command = ['taskset', '-c', str(args.client_cpu), str(client_dir / 'redis-benchmark'),
                       '-h', '127.0.0.1', '-p', str(args.port), '-n', str(args.requests),
                       '-P', str(args.pipeline), '-c', str(args.clients), '--csv', *case['argv']]
            log = destination / 'benchmark.csv'
            errors = destination / 'benchmark.stderr.log'
            run_logged(command, log, cwd=destination, timeout=args.timeout, stderr=errors)
            if process.poll() is not None:
                raise RuntimeError('Redis exited during the benchmark')
            result = parse_benchmark(log.read_text(), errors.read_text())
            result.update(requests=args.requests, clients=args.clients, pipeline=args.pipeline)
            save_json(destination / 'measurement.json', result)
            return result
        finally:
            stop_process(process)


def benchmark_verdict(old, new, threshold):
    slowdown = (Decimal(old['rps']) / Decimal(new['rps']) - 1) * 100
    return str(slowdown), 'benchmark_confirmed' if slowdown >= threshold else 'not_reproduced'


def write_summary(output, results):
    fields = ['id', 'status', 'slowdown_percent', 'error']
    with (output / 'summary.csv').open('w', newline='', encoding='utf-8') as stream:
        writer = csv.DictWriter(stream, fieldnames=fields, extrasaction='ignore')
        writer.writeheader()
        writer.writerows(results)
    save_json(output / 'summary.json', results)


def format_final_report(content):
    """Omit auxiliary diagnostics only inside the generated Original Result block."""
    def trim_result(match):
        lines = match['result'].splitlines(keepends=True)
        for index, line in enumerate(lines):
            if line.strip().lower().rstrip(':') in {'modified part', 'icount diff'}:
                result = ''.join(lines[:index]).rstrip()
                return match['prefix'] + result + '\n' + match['closing']
        return match[0]

    return re.sub(
        r'(?P<prefix>^## Original Result\n\n(?P<fence>`{3,})text\n)'
        r'(?P<result>.*?)(?P<closing>^(?P=fence)$)',
        trim_result, content, flags=re.MULTILINE | re.DOTALL)


def publish_final_reports(output, results, final_dir, selected_only=False):
    accepted = {}
    for result in results:
        if result['status'] in {'direct_report', 'benchmark_confirmed'}:
            name = f"{result['id']}.md"
            match = reporting.REPORT_RE.fullmatch(name)
            if not match:
                raise ValueError(f'Invalid final report name: {name}')
            content = (output / 'reports' / name).read_text(encoding='utf-8')
            accepted[Path(match.group(1)) / name] = FINAL_MARKER + '\n' + format_final_report(content)
    owned = set()
    if final_dir.exists():
        # Recognize both legacy flat reports and reports already grouped by commit.
        candidates = list(final_dir.glob('*.md'))
        for directory in final_dir.iterdir():
            if (reporting.COMMIT_RE.fullmatch(directory.name) and
                    directory.is_dir() and not directory.is_symlink()):
                candidates.extend(directory.glob('*.md'))
        for path in candidates:
            match = reporting.REPORT_RE.fullmatch(path.name)
            if (match and path.is_file() and not path.is_symlink() and
                    (path.parent == final_dir or path.parent.name == match.group(1))):
                with path.open(encoding='utf-8') as stream:
                    if stream.readline().strip() == FINAL_MARKER:
                        owned.add(path.relative_to(final_dir))
    for relative in accepted:
        path = final_dir / relative
        if path.parent.is_symlink() or (path.parent.exists() and not path.parent.is_dir()):
            raise ValueError(f'Invalid final report commit directory: {path.parent}')
        if (path.exists() or path.is_symlink()) and relative not in owned:
            raise ValueError(f'Refusing to overwrite an unowned final report: {path}')
    final_dir.mkdir(parents=True, exist_ok=True)
    for relative, content in accepted.items():
        path = final_dir / relative
        path.parent.mkdir(exist_ok=True)
        path.write_text(content, encoding='utf-8')
    stale = owned - accepted.keys()
    if selected_only:
        selected = {result['id'] for result in results}
        stale = {relative for relative in stale if relative.stem in selected}
    for relative in stale:
        (final_dir / relative).unlink()
    for parent in {relative.parent for relative in stale if relative.parent != Path('.')}:
        directory = final_dir / parent
        if not any(directory.iterdir()):
            directory.rmdir()
    return len(accepted)


def execute(cases, args):
    repo = (args.source_repo or args.root / 'redis').resolve()
    final_dir = (args.final_dir or args.root / 'report-final').resolve()
    if final_dir == (args.report_dir or args.root / 'report').resolve():
        raise ValueError('final report directory must differ from the input report directory')
    if any(case['action'] == 'benchmark' for case in cases):
        for name in ('git', 'make', 'taskset', args.cc):
            if shutil.which(name) is None:
                raise ValueError(f'required executable not found: {name}')
        allowed = os.sched_getaffinity(0)
        if args.server_cpu == args.client_cpu or not {args.server_cpu, args.client_cpu} <= allowed:
            raise ValueError('server/client CPUs must be distinct and available to this process')
        if not repo.is_dir():
            raise ValueError(f'source repository does not exist: {repo}')
    output = (args.output_dir or args.root / 'report-confirmation' /
              datetime.now().strftime('%Y%m%d-%H%M%S-%f')).resolve()
    output.mkdir(parents=True, exist_ok=False)
    for name in ('builds', 'snapshots', 'cases', 'reports'):
        (output / name).mkdir()
    save_json(output / 'plan.json', cases)
    save_json(output / 'settings.json', {key: str(value) if isinstance(value, (Path, Decimal)) else value
                                        for key, value in vars(args).items()})
    results = []
    print(f'Output: {output}', flush=True)
    for case in cases:
        folder = output / 'cases' / case['id']
        folder.mkdir()
        shutil.copyfile(case['report'], folder / 'original-report.md')
        if Path(case['symbolic_file']).is_file():
            shutil.copyfile(case['symbolic_file'], folder / 'symbolic_testcase.txt')
        result = dict(id=case['id'], status=case['action'], slowdown_percent='', error=case['error'])
        result.update(symbolic_slowdown_percent=case['symbolic_slowdown_percent'],
                      default_slowdown_percent=case['default_slowdown_percent'])
        try:
            if case['action'] == 'direct_report':
                note = ('Retained by user rule: symbolic_testcase.txt is nonempty and '
                        f"symbolic-mode slowdown is {Decimal(case['symbolic_slowdown_percent']):+.4f}%, "
                        f'at least the {args.threshold_percent}% threshold. '
                        'No benchmark was run for this case.\n\n' + reporting.fenced(case['symbolic_values']))
            elif case['action'] == 'below_threshold':
                note = 'Neither execution mode meets the screening threshold.'
            elif case['action'] == 'manual_review':
                note = 'Not benchmarked: ' + case['error']
            else:
                print(f"Benchmark: {case['id']} ({args.requests} requests per version, "
                      f"{args.clients} clients, pipeline={args.pipeline}, one round)", flush=True)
                pair = resolve_pair(repo, case['commit'])
                result['versions'] = pair
                bins = {label: build_version(repo, commit, output / 'builds', args)
                        for label, commit in pair.items()}
                snapshot = snapshot_data(case['data_file'], output / 'snapshots')
                # Use one client binary and a fresh copy of the same RDB on both sides.
                old = measure(bins['old'], bins['new'], case, folder / 'old', snapshot, args)
                new = measure(bins['new'], bins['new'], case, folder / 'new', snapshot, args)
                slowdown, status = benchmark_verdict(old, new, args.threshold_percent)
                result.update(status=status, slowdown_percent=slowdown, old=old, new=new)
                note = (f"One round, {args.requests} requests per version, {args.clients} clients, "
                        f"pipeline depth {args.pipeline}.\n\n"
                        f"Old commit: `{pair['old']}`; new commit: `{pair['new']}`.\n\n"
                        f"Old throughput: {old['rps']} requests/s; new throughput: {new['rps']} requests/s.\n\n"
                        f"Elapsed-time slowdown for the same request count: {Decimal(slowdown):+.4f}%.\n\n"
                        f"Formula: (old throughput / new throughput - 1) * 100. Threshold: {args.threshold_percent}%.\n\n"
                        'This compares the whole command workload on clean builds, not instrumented function timings.')
            if result['status'] in {'direct_report', 'benchmark_confirmed'}:
                original = Path(case['report']).read_text(encoding='utf-8')
                (output / 'reports' / f"{case['id']}.md").write_text(
                    original + '\n## Confirmation\n\n' + note + '\n', encoding='utf-8')
            print(f"{case['id']}: {result['status']}", flush=True)
        except (KeyboardInterrupt, SystemExit):
            result.update(status='interrupted', error='Interrupted by user')
            raise
        except (OSError, ValueError, RuntimeError, subprocess.SubprocessError, csv.Error) as error:
            result.update(status='error', error=str(error))
            (folder / 'error.log').write_text(traceback.format_exc(), encoding='utf-8')
            print(f"ERROR {case['id']}: {error}", file=sys.stderr, flush=True)
        finally:
            results.append(result)
            save_json(folder / 'result.json', result)
            write_summary(output, results)
    retained = publish_final_reports(output, results, final_dir, selected_only=bool(args.case))
    print(f'Retained reports: {retained}; final reports: {final_dir}')
    return 1 if any(r['status'] in {'error', 'manual_review'} for r in results) else 0


def parser():
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument('--root', type=Path, default=Path(__file__).resolve().parent)
    result.add_argument('--report-dir', type=Path)
    result.add_argument('--source-repo', type=Path)
    result.add_argument('--output-dir', type=Path, help='must not already exist')
    result.add_argument('--final-dir', type=Path, help='default: ROOT/report-final; refreshed automatically')
    result.add_argument('--case', action='append', help='optional report stem, repeatable')
    mode = result.add_mutually_exclusive_group()
    mode.add_argument('--execute', action='store_true', help='build and run; otherwise only print a plan')
    mode.add_argument('--dry-run', action='store_true', help='explicit read-only plan (the default)')
    data = result.add_mutually_exclusive_group()
    data.add_argument('--data-file', type=Path, help='override the initial RDB for all benchmark cases')
    data.add_argument('--empty-db', action='store_true', help='explicitly use a fresh empty database')
    result.add_argument('--requests', type=positive_int, default=1000000)
    result.add_argument('--clients', type=positive_int, default=50,
                        help='parallel clients (default: 50, matching redis-benchmark)')
    result.add_argument('--pipeline', type=positive_int, default=10,
                        help='pipeline depth passed to redis-benchmark -P (default: 10)')
    result.add_argument('--jobs', type=positive_int, default=4)
    result.add_argument('--cc', default='gcc')
    result.add_argument('--server-cpu', type=int, default=45)
    result.add_argument('--client-cpu', type=int, default=57)
    result.add_argument('--port', type=positive_int, default=16379)
    result.add_argument('--timeout', type=positive_int, default=3600)
    result.add_argument('--startup-timeout', type=positive_int, default=120)
    result.add_argument('--threshold-percent', type=reporting.threshold_percent, default=Decimal('2'))
    return result


def main(argv=None):
    args = parser().parse_args(argv)
    args.root = args.root.resolve()
    if args.data_file:
        args.data_file = args.data_file.resolve()
    try:
        if args.port > 65535:
            raise ValueError('port must be between 1 and 65535')
        cases = load_cases(args)
        for case in cases:
            print(f"{case['action']:14} {case['id']} symbolic={case['symbolic_state']}"
                  + (f" ({case['error']})" if case['error'] else ''))
        counts = {action: sum(case['action'] == action for case in cases)
                  for action in ('direct_report', 'benchmark', 'below_threshold', 'manual_review')}
        print(f'Plan: {counts}; {args.requests} requests/version; {args.clients} clients; '
              f'pipeline={args.pipeline}; one round; threshold={args.threshold_percent}%')
        if not args.execute:
            print('Plan only. No files changed, no build or Redis process started. Use --execute to run.')
            return 0
        return execute(cases, args)
    except KeyboardInterrupt:
        print('Interrupted; owned child processes stopped and available results saved.', file=sys.stderr)
        return 130
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(143))
    sys.exit(main())
