#!/usr/bin/env python3
"""Report Redis slowdowns from existing results; never run experiments.

Usage: python3 generate_perf_report.py [--threshold-percent 2] [--dry-run]
Only commits listed in root/commit are scanned. Each report is named
<commit>-<case>.md. Ratios in final-res.txt are fractions, not percentages.
Commands in root/redis-order-null.txt are excluded from reporting.
"""

import argparse
import csv
from decimal import Decimal, InvalidOperation
from pathlib import Path
import re
import shlex
import sys


DEFAULT_ROOT = Path('/data3/sjz/AE/redis')
MARKER = '<!-- generated by generate_perf_report.py -->'
COMMIT_RE = re.compile(r'[0-9a-fA-F]{40}')
REPORT_RE = re.compile(r'([0-9a-f]{40})-([0-9]+)\.md')
SYMBOLIC = 'New version (symbolic path)'
DEFAULT = 'New version (default execution)'
OLD = 'Old version'
SYMBOLIC_CHANGE = 'New vs. old (symbolic path)'
DEFAULT_CHANGE = 'New vs. old (default execution)'
LABELS = (SYMBOLIC, DEFAULT, OLD, SYMBOLIC_CHANGE, DEFAULT_CHANGE)
LEGACY_LABELS = {
    '\u65b0\u7248\u672c\u6cbf\u7b26\u53f7\u6267\u884c': SYMBOLIC,
    '\u65b0\u7248\u672c\u9ed8\u8ba4\u6267\u884c': DEFAULT,
    '\u65e7\u7248\u672c': OLD,
    '\u65b0\u65e7\u7248\u672c\u6bd4\u8f83\uff08\u6cbf\u7b26\u53f7\u6267\u884c\uff09': SYMBOLIC_CHANGE,
    '\u65b0\u65e7\u7248\u672c\u6bd4\u8f83\uff08\u9ed8\u8ba4\u6267\u884c\uff09': DEFAULT_CHANGE,
}
MODES = ((SYMBOLIC, SYMBOLIC_CHANGE), (DEFAULT, DEFAULT_CHANGE))
SUBCOMMAND_FAMILIES = {'MODULE', 'CONFIG', 'ACL', 'CLUSTER', 'DEBUG', '--CLUSTER'}


def load_commits(directory):
    if not directory.is_dir():
        raise ValueError(f'Commit directory does not exist: {directory}')
    commits = {}
    for path in sorted(directory.iterdir()):
        if not path.is_file() or not path.name.startswith('commit'):
            continue
        with path.open(encoding='utf-8-sig', newline='') as stream:
            for row in csv.reader(stream):
                for cell in row:
                    value = cell.strip()
                    if COMMIT_RE.fullmatch(value):
                        commits.setdefault(value.lower(), None)
    if not commits:
        raise ValueError(f'No full commit hashes found in {directory}')
    return list(commits)


def parse_result(path):
    content = path.read_text(encoding='utf-8')
    lines = [line.strip() for line in content.splitlines() if line.strip()]
    values = {}
    for index, line in enumerate(lines):
        line = LEGACY_LABELS.get(line, line)
        if line not in LABELS:
            continue
        if line in values:
            raise ValueError(f'duplicate field: {line}')
        if index + 1 == len(lines):
            raise ValueError(f'missing value: {line}')
        try:
            value = Decimal(lines[index + 1])
        except InvalidOperation as error:
            raise ValueError(f'invalid number for {line}') from error
        if not value.is_finite():
            raise ValueError(f'non-finite number for {line}')
        values[line] = value
    missing = [label for label in LABELS if label not in values]
    if missing:
        raise ValueError('incomplete end-to-end results: ' + ', '.join(missing))
    for label in (SYMBOLIC, DEFAULT, OLD):
        if values[label] <= 0:
            raise ValueError(f'non-positive execution time: {label}')
    for mode, change in MODES:
        calculated = (values[mode] - values[OLD]) / values[OLD]
        if abs(calculated - values[change]) > Decimal('0.000001'):
            raise ValueError(f'ratio disagrees with execution times: {change}')
    return values, content


def command_key(command):
    command = command.strip()
    if command.startswith('testcase:'):
        command = command[len('testcase:'):].strip()
    args = shlex.split(command)
    if not args:
        raise ValueError('empty testcase command')
    executable = Path(args[0]).name.lower()
    if executable == 'redis-server':
        return ('REDIS-SERVER',)
    if executable == 'redis-cli':
        args = args[1:]
    if not args:
        raise ValueError('redis-cli has no command')
    name = args[0].upper()
    if name in SUBCOMMAND_FAMILIES:
        if len(args) < 2:
            raise ValueError(f'{name} has no subcommand')
        return (name, args[1].upper())
    if name in {'INFO', 'REPLCONF'}:
        return (name,)
    return (name, *args[1:])


def load_exclusions(path):
    exclusions = set()
    for number, line in enumerate(path.read_text(encoding='utf-8-sig').splitlines(), 1):
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        try:
            exclusions.add(command_key(line))
        except ValueError as error:
            raise ValueError(f'{path}:{number}: {error}') from error
    return exclusions


def load_case_commands(directory):
    path = directory / 'call_analyse2.txt'
    if not path.is_file():
        return {}
    groups = {True: [], False: []}
    is_null = False
    for block in re.split(r'\n\s*\n', path.read_text(encoding='utf-8').strip()):
        marker = block.strip().upper()
        if marker in {'BEGIN NULL', 'END NULL'}:
            is_null = marker == 'BEGIN NULL'
            continue
        for line in block.splitlines():
            line = line.strip()
            if line.startswith('testcase:'):
                command = line[len('testcase:'):].strip()
                if command and command != 'no testcase':
                    groups[is_null].append(command)
                break
    # The runner handles NULL blocks first. Startup/DEBUG skips still use an index.
    return {str(index): command for index, command in
            enumerate(groups[True] + groups[False], 1)}


def read_case_command(path, fallback):
    directory = path.parent.parent
    case = path.parent.name
    for suffix in ('', '-1', '-2'):
        candidate = directory / 'src' / (case + suffix) / 'bin/get_redis_3.txt'
        if candidate.is_file():
            content = candidate.read_text(encoding='utf-8').strip()
            if content:
                return content.splitlines()[-1].strip()
    return fallback.get(case, '')


def percent(ratio):
    return f'{ratio * 100:+.4f}%'


def fenced(content):
    longest = max((len(match) for match in re.findall(r'`+', content)), default=0)
    fence = '`' * max(3, longest + 1)
    return f'{fence}text\n{content.rstrip()}\n{fence}'


def render_report(commit, case, path, values, content, threshold, command):
    hits = [mode for mode, change in MODES if values[change] >= threshold]
    lines = [
        MARKER, f'# Potential Performance Regression: {commit} / {case}', '',
        f'- Commit: `{commit}`', f'- Case: `{case}`',
        f'- Source: `{path}`',
        f'- Threshold: slowdown >= {threshold * 100:g}%',
        '- Flagged modes: ' + ', '.join(hits), '',
        '| Execution mode | New (us) | Old (us) | Slowdown | >= threshold |',
        '| --- | ---: | ---: | ---: | --- |',
    ]
    for mode, change in MODES:
        lines.append(
            f'| {mode} | {values[mode]:.6f} | {values[OLD]:.6f} | '
            f'{percent(values[change])} | {"YES" if mode in hits else "no"} |')
    lines += ['', 'Positive percentages mean slower than the old version.',
              'These are screening candidates, not confirmed regressions.']

    if command:
        lines += ['', '## Test Command', '', fenced(command)]
    else:
        lines += ['', 'Test command unavailable; exclusion matching could not be verified.']

    if SYMBOLIC in hits:
        symbolic_path = path.parent / 'symbolic_testcase.txt'
        lines += ['', '## Symbolic Values', '', f'Source: `{symbolic_path}`', '']
        if not symbolic_path.is_file():
            lines.append('symbolic_testcase.txt is missing. No symbolic values are available; '
                         'the symbolic-mode timing alone does not establish a symbolic input.')
        else:
            symbolic = symbolic_path.read_text(encoding='utf-8').strip()
            lines.append(fenced(symbolic) if symbolic else
                         'symbolic_testcase.txt is empty. No symbolic values were generated; '
                         'the symbolic-mode timing alone does not establish a symbolic input.')
    lines += ['', '## Original Result', '', fenced(content), '']
    return '\n'.join(lines)


def collect_reports(root, commits, threshold, exclusions=()):
    reports = {}
    counts = dict(commits=len(commits), missing_commits=0, result_files=0,
                  incomplete_cases=0, invalid_results=0, below_threshold=0,
                  excluded_cases=0, unknown_commands=0)
    for commit in commits:
        directory = root / f'redis-{commit}'
        if not directory.is_dir():
            counts['missing_commits'] += 1
            continue
        commands = load_case_commands(directory)
        cases = sorted((item for item in directory.iterdir()
                        if item.is_dir() and re.fullmatch(r'[0-9]+', item.name)),
                       key=lambda item: int(item.name))
        for case in cases:
            path = case / 'final-res.txt'
            if not path.is_file():
                counts['incomplete_cases'] += 1
                continue
            counts['result_files'] += 1
            try:
                values, content = parse_result(path)
            except (ValueError, OSError) as error:
                counts['invalid_results'] += 1
                print(f'SKIP {path}: {error}', file=sys.stderr)
                continue
            command = read_case_command(path, commands)
            try:
                excluded = command_key(command) in exclusions
            except ValueError as error:
                counts['unknown_commands'] += 1
                print(f'WARNING {path}: command filter not applied: {error}', file=sys.stderr)
                excluded = False
            if excluded:
                counts['excluded_cases'] += 1
                print(f'EXCLUDE {commit}/{case.name}: {command}')
                continue
            if not any(values[change] >= threshold for _, change in MODES):
                counts['below_threshold'] += 1
                continue
            name = f'{commit}-{case.name}.md'
            reports[name] = render_report(commit, case.name, path, values, content, threshold, command)
            print(f'FLAG {commit}/{case.name}: symbolic={percent(values[SYMBOLIC_CHANGE])}, '
                  f'default={percent(values[DEFAULT_CHANGE])}')
    return reports, counts


def write_reports(output, reports, commits):
    owned = set()
    commit_set = set(commits)
    if output.exists():
        for path in output.iterdir():
            match = REPORT_RE.fullmatch(path.name)
            if match and match[1] in commit_set and path.is_file():
                with path.open(encoding='utf-8') as stream:
                    if stream.readline().strip() == MARKER:
                        owned.add(path.name)
    # Refresh only this script's reports; never overwrite unrelated files.
    for name in reports:
        if (output / name).exists() and name not in owned:
            raise ValueError(f'Refusing to overwrite an unowned report: {output / name}')
    output.mkdir(parents=True, exist_ok=True)
    for name, content in reports.items():
        (output / name).write_text(content, encoding='utf-8')
    for name in owned - reports.keys():
        (output / name).unlink()


def threshold_percent(value):
    try:
        number = Decimal(value)
    except InvalidOperation as error:
        raise argparse.ArgumentTypeError('threshold must be a number') from error
    if not number.is_finite() or number <= 0:
        raise argparse.ArgumentTypeError('threshold must be finite and positive')
    return number


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=DEFAULT_ROOT)
    parser.add_argument('--output-dir', type=Path,
                        help='default: ROOT/report; only generated reports are refreshed')
    parser.add_argument('--exclude-file', type=Path,
                        help='default: ROOT/redis-order-null.txt')
    parser.add_argument('--threshold-percent', type=threshold_percent, default=Decimal('2'),
                        help='inclusive slowdown percentage, default: 2')
    parser.add_argument('--dry-run', action='store_true', help='scan without writing reports')
    args = parser.parse_args(argv)
    root = args.root.resolve()
    output = (args.output_dir or root / 'report').resolve()
    try:
        commits = load_commits(root / 'commit')
        exclusions = load_exclusions(args.exclude_file or root / 'redis-order-null.txt')
        reports, counts = collect_reports(root, commits, args.threshold_percent / 100, exclusions)
        if not args.dry_run:
            write_reports(output, reports, commits)
    except (OSError, ValueError, csv.Error) as error:
        parser.exit(1, f'ERROR: {error}\n')
    print(f'Commits listed: {counts["commits"]}; absent result directories: '
          f'{counts["missing_commits"]}; result files: {counts["result_files"]}')
    print(f'Cases without final-res.txt (skipped or unfinished): {counts["incomplete_cases"]}; '
          f'invalid results: {counts["invalid_results"]}; '
          f'below threshold: {counts["below_threshold"]}')
    print(f'Excluded commands: {counts["excluded_cases"]}; '
          f'unrecognized/missing commands: {counts["unknown_commands"]}')
    print(f'{"Would write" if args.dry_run else "Wrote"} {len(reports)} reports to {output}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
